"""Section-label null control for exp-005.

This script reuses the cleaned IVTFF parser policy from exp-002b and the
folio-to-section mapping used by exp-003/exp-004. It compares observed section
distances against null distributions generated by random label assignment.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import random
import re
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from statistics import median


LINE_RE = re.compile(r"^<(?P<locator>[^>;]+;(?P<code>[A-Z]))>\s*(?P<text>.*)$")
PAGE_HEADER_RE = re.compile(r"^<(?P<folio>f[^.>]+)>\s+<!\s*(?P<vars>[^>]*)>")
VAR_RE = re.compile(r"\$(?P<key>[A-Z])=(?P<value>[^ $\t>]+)")
COMMENT_RE = re.compile(r"\{[^}]*\}")
ANGLE_TAG_RE = re.compile(r"<[^>]*>")
TOKEN_SPLIT_RE = re.compile(r"[.,\s]+")

SECTION_CODE_MAP = {
    "T": "text",
    "H": "herbal",
    "A": "astronomical",
    "Z": "zodiac",
    "B": "biological",
    "C": "cosmological",
    "P": "pharmaceutical",
    "S": "stars",
}


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_csv(path: Path, rows: list[dict[str, object]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def normalize_token(raw_token: str) -> str:
    return re.sub(r"[^A-Za-z]", "", raw_token).lower()


def clean_text(text: str, stats: Counter[str]) -> str:
    without_comments = COMMENT_RE.sub("", text)
    tags = ANGLE_TAG_RE.findall(without_comments)
    if tags:
        stats["lines_with_angle_tags"] += 1
        stats["angle_tags_removed"] += len(tags)
        for tag in tags:
            stats[f"angle_tag::{tag}"] += 1
    return ANGLE_TAG_RE.sub(".", without_comments)


def tokenize_clean_line(text: str, stats: Counter[str]) -> list[str]:
    cleaned = clean_text(text, stats)
    tokens: list[str] = []
    for raw_token in TOKEN_SPLIT_RE.split(cleaned):
        token = normalize_token(raw_token)
        if token:
            tokens.append(token)
        elif raw_token:
            stats["discarded_empty_tokens"] += 1
    return tokens


def extract_folio_from_locator(locator: str) -> str:
    return locator.split(";", 1)[0].split(".", 1)[0]


def derive_metadata(input_path: Path, metadata_path: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    with input_path.open("r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            match = PAGE_HEADER_RE.match(line)
            if not match:
                continue
            variables = {item.group("key"): item.group("value") for item in VAR_RE.finditer(match.group("vars"))}
            illustration_code = variables.get("I", "")
            section = SECTION_CODE_MAP.get(illustration_code, "unknown")
            rows.append(
                {
                    "folio_id": match.group("folio"),
                    "section": section,
                    "illustration_code": illustration_code,
                    "quire": variables.get("Q", ""),
                    "page_in_quire": variables.get("P", ""),
                    "currier_language": variables.get("L", ""),
                    "currier_hand": variables.get("H", ""),
                    "source": "data/raw/LSI_ivtff_0d.txt page header parsable information; source documentation https://www.voynich.nu/transcr.html",
                    "note": "Derived from IVTFF page header $I illustration type. Code meanings are documented in the IVTFF file comments.",
                }
            )
    write_csv(
        metadata_path,
        rows,
        [
            "folio_id",
            "section",
            "illustration_code",
            "quire",
            "page_in_quire",
            "currier_language",
            "currier_hand",
            "source",
            "note",
        ],
    )
    return rows


def load_or_create_metadata(input_path: Path, metadata_path: Path) -> tuple[dict[str, dict[str, str]], bool]:
    if metadata_path.exists():
        created = False
        with metadata_path.open("r", encoding="utf-8", newline="") as handle:
            rows = list(csv.DictReader(handle))
    else:
        created = True
        rows = derive_metadata(input_path, metadata_path)
    return {row["folio_id"]: row for row in rows}, created


def parse_selected_lines(
    input_path: Path,
    transcriber_code: str,
    metadata: dict[str, dict[str, str]],
) -> tuple[list[dict[str, object]], list[dict[str, str]], dict[str, int]]:
    parsed_rows: list[dict[str, object]] = []
    unmapped_rows: list[dict[str, str]] = []
    stats: Counter[str] = Counter()

    with input_path.open("r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            stats["input_lines"] += 1
            match = LINE_RE.match(line)
            if not match:
                continue
            stats["data_lines"] += 1
            if match.group("code") != transcriber_code:
                continue

            stats["selected_lines"] += 1
            locator = match.group("locator")
            folio_id = extract_folio_from_locator(locator)
            tokens = tokenize_clean_line(match.group("text"), stats)
            if tokens:
                stats["non_empty_selected_lines"] += 1
            else:
                stats["empty_selected_lines"] += 1

            metadata_row = metadata.get(folio_id)
            if not metadata_row:
                stats["unmapped_selected_lines"] += 1
                unmapped_rows.append({"locator": locator, "folio_id": folio_id, "reason": "folio_id not present in metadata"})
                continue

            stats["mapped_selected_lines"] += 1
            if tokens:
                parsed_rows.append(
                    {
                        "locator": locator,
                        "folio_id": folio_id,
                        "section": metadata_row["section"],
                        "tokens": tokens,
                    }
                )

    public_stats = {key: value for key, value in stats.items() if not key.startswith("angle_tag::")}
    public_stats["unique_angle_tag_forms_removed"] = sum(1 for key in stats if key.startswith("angle_tag::"))
    return parsed_rows, unmapped_rows, public_stats


def build_section_tokens(parsed_rows: list[dict[str, object]]) -> tuple[dict[str, list[str]], dict[str, int]]:
    section_tokens: dict[str, list[str]] = defaultdict(list)
    section_lines: Counter[str] = Counter()
    for row in parsed_rows:
        section = str(row["section"])
        section_lines[section] += 1
        section_tokens[section].extend(row["tokens"])
    return dict(section_tokens), dict(section_lines)


def distribution(counter: Counter[str], vocabulary: set[str]) -> list[float]:
    total = sum(counter.values())
    if total == 0:
        return [0.0 for _ in vocabulary]
    return [counter[token] / total for token in vocabulary]


def kl_divergence(p_dist: list[float], q_dist: list[float]) -> float:
    return sum(p * math.log2(p / q) for p, q in zip(p_dist, q_dist) if p > 0 and q > 0)


def jensen_shannon_divergence(counter_a: Counter[str], counter_b: Counter[str]) -> float:
    vocabulary = set(counter_a) | set(counter_b)
    p_dist = distribution(counter_a, vocabulary)
    q_dist = distribution(counter_b, vocabulary)
    midpoint = [(p + q) / 2 for p, q in zip(p_dist, q_dist)]
    return 0.5 * kl_divergence(p_dist, midpoint) + 0.5 * kl_divergence(q_dist, midpoint)


def quantile(values: list[float], probability: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    position = (len(ordered) - 1) * probability
    lower = math.floor(position)
    upper = math.ceil(position)
    if lower == upper:
        return ordered[lower]
    fraction = position - lower
    return ordered[lower] * (1 - fraction) + ordered[upper] * fraction


def summarize_distribution(values: list[float]) -> dict[str, float]:
    mean_value = sum(values) / len(values) if values else 0.0
    variance = sum((value - mean_value) ** 2 for value in values) / len(values) if values else 0.0
    return {
        "mean": mean_value,
        "std": math.sqrt(variance),
        "median": median(values) if values else 0.0,
        "q025": quantile(values, 0.025),
        "q975": quantile(values, 0.975),
    }


def empirical_p_value(values: list[float], observed: float) -> float:
    return (1 + sum(1 for value in values if value >= observed)) / (len(values) + 1)


def empirical_percentile(values: list[float], observed: float) -> float:
    if not values:
        return 0.0
    return sum(1 for value in values if value <= observed) / len(values)


def conclusion_label(observed: float, summary: dict[str, float]) -> str:
    if observed > summary["q975"]:
        return "above_null_97_5"
    if observed < summary["mean"]:
        return "below_null_mean"
    return "within_null_interval"


def load_json(path: Path) -> object:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def section_pairs(sections: list[str]) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for index, left in enumerate(sections):
        for right in sections[index + 1 :]:
            pairs.append((left, right))
    return pairs


def sample_counter(tokens: list[str], sample_size: int, rng: random.Random) -> Counter[str]:
    return Counter(rng.sample(tokens, sample_size))


def pooled_null_counter(pool: list[str], size_a: int, size_b: int, rng: random.Random) -> tuple[Counter[str], Counter[str]]:
    sample = rng.sample(pool, size_a + size_b)
    return Counter(sample[:size_a]), Counter(sample[size_a:size_a + size_b])


def run_pairwise_null_control(
    section_tokens: dict[str, list[str]],
    iterations: int,
    rng: random.Random,
) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for left, right in section_pairs(sorted(section_tokens)):
        tokens_a = section_tokens[left]
        tokens_b = section_tokens[right]
        observed = jensen_shannon_divergence(Counter(tokens_a), Counter(tokens_b))
        pooled_tokens = tokens_a + tokens_b
        null_values: list[float] = []
        for _ in range(iterations):
            null_a, null_b = pooled_null_counter(pooled_tokens, len(tokens_a), len(tokens_b), rng)
            null_values.append(jensen_shannon_divergence(null_a, null_b))
        summary = summarize_distribution(null_values)
        percentile = empirical_percentile(null_values, observed)
        p_value = empirical_p_value(null_values, observed)
        rows.append(
            {
                "section_a": left,
                "section_b": right,
                "token_count_a": len(tokens_a),
                "token_count_b": len(tokens_b),
                "observed_jsd_bits": observed,
                "null_jsd_mean_bits": summary["mean"],
                "null_jsd_std_bits": summary["std"],
                "null_jsd_median_bits": summary["median"],
                "null_jsd_q025_bits": summary["q025"],
                "null_jsd_q975_bits": summary["q975"],
                "observed_minus_null_mean_bits": observed - summary["mean"],
                "empirical_percentile": percentile,
                "empirical_p_value": p_value,
                "null_conclusion_label": conclusion_label(observed, summary),
            }
        )
    return rows


def load_exp004_pairwise_matched(path: Path) -> dict[tuple[str, str], dict[str, object]]:
    if not path.exists():
        return {}
    data = load_json(path)
    lookup: dict[tuple[str, str], dict[str, object]] = {}
    for row in data:
        key = tuple(sorted((row["section_a"], row["section_b"])))
        lookup[key] = row
    return lookup


def run_pairwise_matched_null_control(
    section_tokens: dict[str, list[str]],
    exp004_lookup: dict[tuple[str, str], dict[str, object]],
    iterations: int,
    rng: random.Random,
) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for left, right in section_pairs(sorted(section_tokens)):
        tokens_a = section_tokens[left]
        tokens_b = section_tokens[right]
        pair_size = min(len(tokens_a), len(tokens_b))
        observed_full = jensen_shannon_divergence(Counter(tokens_a), Counter(tokens_b))
        pooled_tokens = tokens_a + tokens_b
        null_values: list[float] = []
        for _ in range(iterations):
            null_a, null_b = pooled_null_counter(pooled_tokens, pair_size, pair_size, rng)
            null_values.append(jensen_shannon_divergence(null_a, null_b))
        summary = summarize_distribution(null_values)
        exp004_row = exp004_lookup.get(tuple(sorted((left, right))))
        observed_matched_mean = float(exp004_row["jsd_mean_bits"]) if exp004_row else None
        observed_reference = observed_matched_mean if observed_matched_mean is not None else observed_full
        percentile = empirical_percentile(null_values, observed_reference)
        p_value = empirical_p_value(null_values, observed_reference)
        rows.append(
            {
                "section_a": left,
                "section_b": right,
                "token_count_a": len(tokens_a),
                "token_count_b": len(tokens_b),
                "pairwise_sample_size": pair_size,
                "observed_full_jsd_bits": observed_full,
                "exp004_pairwise_matched_mean_jsd_bits": observed_matched_mean if observed_matched_mean is not None else "",
                "matched_null_jsd_mean_bits": summary["mean"],
                "matched_null_jsd_std_bits": summary["std"],
                "matched_null_jsd_median_bits": summary["median"],
                "matched_null_jsd_q025_bits": summary["q025"],
                "matched_null_jsd_q975_bits": summary["q975"],
                "observed_reference_minus_null_mean_bits": observed_reference - summary["mean"],
                "matched_empirical_percentile": percentile,
                "matched_empirical_p_value": p_value,
                "matched_null_conclusion_label": conclusion_label(observed_reference, summary),
            }
        )
    return rows


def run_global_permutation_control(
    section_tokens: dict[str, list[str]],
    iterations: int,
    rng: random.Random,
) -> dict[str, object]:
    sections = sorted(section_tokens)
    observed_rows = [
        jensen_shannon_divergence(Counter(section_tokens[left]), Counter(section_tokens[right]))
        for left, right in section_pairs(sections)
    ]
    observed_mean = sum(observed_rows) / len(observed_rows) if observed_rows else 0.0
    pooled_tokens: list[str] = []
    section_sizes: dict[str, int] = {}
    for section in sections:
        section_sizes[section] = len(section_tokens[section])
        pooled_tokens.extend(section_tokens[section])

    null_means: list[float] = []
    total_size = len(pooled_tokens)
    for _ in range(iterations):
        sample = rng.sample(pooled_tokens, total_size)
        reassigned: dict[str, list[str]] = {}
        cursor = 0
        for section in sections:
            size = section_sizes[section]
            reassigned[section] = sample[cursor:cursor + size]
            cursor += size
        null_values = [
            jensen_shannon_divergence(Counter(reassigned[left]), Counter(reassigned[right]))
            for left, right in section_pairs(sections)
        ]
        null_means.append(sum(null_values) / len(null_values) if null_values else 0.0)

    summary = summarize_distribution(null_means)
    return {
        "observed_mean_pairwise_jsd_bits": observed_mean,
        "null_mean_pairwise_jsd_mean_bits": summary["mean"],
        "null_mean_pairwise_jsd_std_bits": summary["std"],
        "null_mean_pairwise_jsd_median_bits": summary["median"],
        "null_mean_pairwise_jsd_q025_bits": summary["q025"],
        "null_mean_pairwise_jsd_q975_bits": summary["q975"],
        "observed_minus_null_mean_bits": observed_mean - summary["mean"],
        "empirical_percentile": empirical_percentile(null_means, observed_mean),
        "empirical_p_value": empirical_p_value(null_means, observed_mean),
    }


def json_ready(value: object) -> object:
    if isinstance(value, Path):
        return str(value.as_posix())
    if isinstance(value, dict):
        return {str(key): json_ready(item) for key, item in value.items()}
    if isinstance(value, list):
        return [json_ready(item) for item in value]
    return value


def main() -> int:
    parser = argparse.ArgumentParser(description="Run exp-005 section-label null control.")
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--metadata", default=Path("data/metadata/folio_sections.csv"), type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--transcriber-code", default="H")
    parser.add_argument("--iterations", type=int, default=1000)
    parser.add_argument("--seed", type=int, default=20260621)
    parser.add_argument("--min-count", type=int, default=10)
    parser.add_argument("--top-n", type=int, default=30)
    parser.add_argument("--sample-mode", default="pairwise-matched")
    parser.add_argument("--exp003-observed", default=Path("artifacts/exp003/pairwise_section_distances.json"), type=Path)
    parser.add_argument("--exp004-pairwise-matched", default=Path("artifacts/exp004/pairwise_matched_jsd.json"), type=Path)
    args = parser.parse_args()

    args.output.mkdir(parents=True, exist_ok=True)
    metadata, metadata_created = load_or_create_metadata(args.input, args.metadata)
    parsed_rows, unmapped_rows, parse_stats = parse_selected_lines(args.input, args.transcriber_code, metadata)
    section_tokens, section_lines = build_section_tokens(parsed_rows)
    sections = sorted(section_tokens)
    section_count_rows = [
        {"section": section, "line_count": section_lines[section], "token_count": len(section_tokens[section])}
        for section in sections
    ]
    write_csv(args.output / "section_token_counts.csv", section_count_rows, ["section", "line_count", "token_count"])
    write_csv(args.output / "unmapped_lines.csv", unmapped_rows, ["locator", "folio_id", "reason"])

    rng_pairwise = random.Random(args.seed)
    rng_matched = random.Random(args.seed + 1)
    rng_global = random.Random(args.seed + 2)

    pairwise_rows = run_pairwise_null_control(section_tokens, args.iterations, rng_pairwise)
    write_csv(
        args.output / "pairwise_null_control.csv",
        pairwise_rows,
        [
            "section_a",
            "section_b",
            "token_count_a",
            "token_count_b",
            "observed_jsd_bits",
            "null_jsd_mean_bits",
            "null_jsd_std_bits",
            "null_jsd_median_bits",
            "null_jsd_q025_bits",
            "null_jsd_q975_bits",
            "observed_minus_null_mean_bits",
            "empirical_percentile",
            "empirical_p_value",
            "null_conclusion_label",
        ],
    )
    with (args.output / "pairwise_null_control.json").open("w", encoding="utf-8") as handle:
        json.dump(pairwise_rows, handle, indent=2)
        handle.write("\n")

    comparison_rows = [
        {
            "section_a": row["section_a"],
            "section_b": row["section_b"],
            "observed_jsd_bits": row["observed_jsd_bits"],
            "null_jsd_mean_bits": row["null_jsd_mean_bits"],
            "observed_minus_null_mean_bits": row["observed_minus_null_mean_bits"],
            "null_jsd_q025_bits": row["null_jsd_q025_bits"],
            "null_jsd_q975_bits": row["null_jsd_q975_bits"],
            "empirical_percentile": row["empirical_percentile"],
            "empirical_p_value": row["empirical_p_value"],
            "null_conclusion_label": row["null_conclusion_label"],
        }
        for row in pairwise_rows
    ]
    write_csv(
        args.output / "observed_vs_null_jsd.csv",
        comparison_rows,
        [
            "section_a",
            "section_b",
            "observed_jsd_bits",
            "null_jsd_mean_bits",
            "observed_minus_null_mean_bits",
            "null_jsd_q025_bits",
            "null_jsd_q975_bits",
            "empirical_percentile",
            "empirical_p_value",
            "null_conclusion_label",
        ],
    )

    exp004_lookup = load_exp004_pairwise_matched(args.exp004_pairwise_matched)
    matched_rows = run_pairwise_matched_null_control(section_tokens, exp004_lookup, args.iterations, rng_matched)
    write_csv(
        args.output / "pairwise_matched_null_control.csv",
        matched_rows,
        [
            "section_a",
            "section_b",
            "token_count_a",
            "token_count_b",
            "pairwise_sample_size",
            "observed_full_jsd_bits",
            "exp004_pairwise_matched_mean_jsd_bits",
            "matched_null_jsd_mean_bits",
            "matched_null_jsd_std_bits",
            "matched_null_jsd_median_bits",
            "matched_null_jsd_q025_bits",
            "matched_null_jsd_q975_bits",
            "observed_reference_minus_null_mean_bits",
            "matched_empirical_percentile",
            "matched_empirical_p_value",
            "matched_null_conclusion_label",
        ],
    )
    with (args.output / "pairwise_matched_null_control.json").open("w", encoding="utf-8") as handle:
        json.dump(matched_rows, handle, indent=2)
        handle.write("\n")

    global_summary = run_global_permutation_control(section_tokens, args.iterations, rng_global)
    write_csv(args.output / "global_section_label_permutation.csv", [global_summary], list(global_summary.keys()))
    with (args.output / "global_section_label_permutation.json").open("w", encoding="utf-8") as handle:
        json.dump(global_summary, handle, indent=2)
        handle.write("\n")

    observed_exp003 = load_json(args.exp003_observed) if args.exp003_observed.exists() else []
    observed_exp003_values = [row["jensen_shannon_divergence_bits"] for row in observed_exp003]
    exp004_rows = load_json(args.exp004_pairwise_matched) if args.exp004_pairwise_matched.exists() else []
    exp004_values = [row["jsd_mean_bits"] for row in exp004_rows]

    run_summary = {
        "experiment": "exp-005_section-label-null-control",
        "run_date_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "script": "scripts/exp005_section_label_null_control.py",
        "input": args.input,
        "input_sha256": file_sha256(args.input),
        "metadata": args.metadata,
        "metadata_created_by_script": metadata_created,
        "metadata_source": "Reuse exp-003/exp-004 folio-to-section mapping derived from IVTFF page headers ($I illustration type).",
        "output": args.output,
        "parameters": {
            "transcriber_code": args.transcriber_code,
            "iterations": args.iterations,
            "seed": args.seed,
            "min_count": args.min_count,
            "top_n": args.top_n,
            "sample_mode": args.sample_mode,
            "parser_policy": "cleaned exp-002b policy: remove comments, replace inline <...> markup with token boundaries, split on periods/commas/whitespace, lowercase and strip non-ASCII letters",
            "pairwise_null_control": "pooled-label, size-matched to observed full section sizes",
            "pairwise_matched_null_control": "pooled-label, size-matched to exp-004 pairwise matched sample sizes",
            "global_permutation_control": "all-section pooled-label reassignment preserving section token counts",
        },
        "parse_stats": parse_stats,
        "section_count": len(sections),
        "sections": sections,
        "section_token_counts": section_count_rows,
        "historical_observed_exp003_mean_pairwise_jsd_bits": (sum(observed_exp003_values) / len(observed_exp003_values)) if observed_exp003_values else None,
        "historical_exp004_pairwise_matched_mean_pairwise_jsd_bits": (sum(exp004_values) / len(exp004_values)) if exp004_values else None,
        "pairwise_null_control_rows": len(pairwise_rows),
        "pairwise_matched_null_control_rows": len(matched_rows),
        "global_section_label_permutation": global_summary,
        "artifacts": [
            "run_summary.json",
            "section_token_counts.csv",
            "pairwise_null_control.csv",
            "pairwise_null_control.json",
            "observed_vs_null_jsd.csv",
            "pairwise_matched_null_control.csv",
            "pairwise_matched_null_control.json",
            "global_section_label_permutation.csv",
            "global_section_label_permutation.json",
            "unmapped_lines.csv",
        ],
    }
    with (args.output / "run_summary.json").open("w", encoding="utf-8") as handle:
        json.dump(json_ready(run_summary), handle, indent=2)
        handle.write("\n")

    pairwise_above = sum(1 for row in pairwise_rows if row["null_conclusion_label"] == "above_null_97_5")
    matched_above = sum(1 for row in matched_rows if row["matched_null_conclusion_label"] == "above_null_97_5")
    print(
        json.dumps(
            {
                "section_count": len(sections),
                "pairwise_pairs": len(pairwise_rows),
                "pairwise_above_null_97_5": pairwise_above,
                "matched_above_null_97_5": matched_above,
                "global_observed_mean_pairwise_jsd_bits": global_summary["observed_mean_pairwise_jsd_bits"],
                "global_null_mean_pairwise_jsd_mean_bits": global_summary["null_mean_pairwise_jsd_mean_bits"],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
